### ISSUE TITLE
[1.19.2] [Fabric] Cant create a new world

### ISSUE THREAD

**Issue by pewblaze** [ThatGravyBoat/Cozy#2]
Hi, i cant create a new world (Singleplayer). Its stuck somewhere & after that its not loading anymore.
It works fine without the mod. 

latest.log:
https://gist.github.com/pewblaze/bb9584383a38db39a1cece460d0ef40e

**Comment by ThatGravyBoat** [comment]
Fixed just uploaded the fixed version should be released in about 10-20 min.

**Comment by ThatGravyBoat** [comment]
Here: https://www.curseforge.com/minecraft/mc-mods/cozy/files/3924537
